test_that("save_plot: works", {
    plot <- ggplot2::qplot(1:10, 1:10)
    prefix <- tempfile()
    save_plot(plot, prefix)
    pngfile <- paste0(prefix, ".png")
    pdffile <- paste0(prefix, ".pdf")
    expect_true(file.exists(pngfile))
    expect_true(file.exists(pdffile))
    unlink(pngfile)
    unlink(pdffile)
})

test_that("save_plot: works with height/width attributes", {
    plot <- ggplot2::qplot(1:10, 1:10)
    attr(plot, "width") <- 8
    attr(plot, "height") <- 6
    prefix <- tempfile()
    save_plot(plot, prefix)
    pngfile <- paste0(prefix, ".png")
    pdffile <- paste0(prefix, ".pdf")
    expect_true(file.exists(pngfile))
    expect_true(file.exists(pdffile))
    unlink(pngfile)
    unlink(pdffile)
})

test_that("save_plotcode: must have plot generated by gglogger registered", {
    expect_error(save_plotcode(ggplot2::qplot(1:10, 1:10), tempfile()))
})

test_that("save_plotcode: works with no variables", {
    qplot <- gglogger::register(ggplot2::qplot)
    plot <- qplot(1:10, 1:10)
    prefix <- tempfile()
    save_plotcode(plot, prefix)
    zipfile <- paste0(prefix, ".code.zip")
    expect_true(file.exists(zipfile))
    filelist <- zip::zip_list(zipfile)
    expect_true("plot.R" %in% filelist$filename)
    expect_true(!"data.RData" %in% filelist$filename)
    unlink(zipfile)
})

test_that("save_plotcode: works with variables", {
    qplot <- gglogger::register(ggplot2::qplot)
    x <- y <- 1:10
    plot <- qplot(x, y)
    prefix <- tempfile()
    save_plotcode(plot, prefix, "x", "y")
    zipfile <- paste0(prefix, ".code.zip")
    expect_true(file.exists(zipfile))
    filelist <- zip::zip_list(zipfile)
    expect_true("plot.R" %in% filelist$filename)
    expect_true("data.RData" %in% filelist$filename)
    unlink(zipfile)
})

test_that("save_plotcode: saved code reproduces plot", {
    qplot <- gglogger::register(ggplot2::qplot)
    x <- y <- 1:10
    plot <- qplot(x, y)
    prefix <- tempfile()
    save_plotcode(plot, prefix, setup = "", "x", "y")
    zipfile <- paste0(prefix, ".code.zip")
    wdir <- tempdir()
    zip::unzip(zipfile, exdir = wdir)
    codefile <- file.path(wdir, "plot.R")
    lines <- readLines(codefile)
    expect_true('load("data.RData")' %in% lines)
    expect_true('ggplot2::qplot(x, y)' %in% lines)
    setwd(wdir)
    plot2 <- source(codefile)$value
    # plot equals?
    expect_equal(plot$data, plot2$data)
    unlink(zipfile)
})
