package:
  name: r-biopipen.utils
  version: 0.0.7

source:
  git_url: https://github.com/pwwang/biopipen.utils.R
  git_rev: 0.0.7

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-bracer
    - r-clustree
    - r-concaveman
    - r-digest
    - r-doubletfinder
    - r-dplyr
    - r-enrichr
    - r-ggplot2
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-inext
    - r-jsonlite
    - r-logger
    - r-matrix
    - r-r6
    - r-rlang
    - r-scales
    - r-seurat
    - r-seuratobject
    - r-scattermore
    - r-testthat
    - r-tibble
    - r-tidyr
    - r-tidyseurat
    - r-zip
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-complexheatmap
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - pwwang::r-plotthis
    - pwwang::r-scplotter
    - pwwang::r-gglogger

  run:
    - r-base
    - r-bracer
    - r-clustree
    - r-concaveman
    - r-digest
    - r-doubletfinder
    - r-dplyr
    - r-enrichr
    - r-ggplot2
    - r-ggwordcloud
    - r-ggalluvial
    - r-ggvenndiagram
    - r-ggupset
    - r-ggpubr
    - r-ggforce
    - r-ggraph
    - r-ggridges
    - r-hexbin
    - r-igraph
    - r-inext
    - r-jsonlite
    - r-logger
    - r-matrix
    - r-r6
    - r-rlang
    - r-scales
    - r-seurat
    - r-seuratobject
    - r-scattermore
    - r-testthat
    - r-tibble
    - r-tidyr
    - r-tidyseurat
    - r-zip
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-complexheatmap
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - pwwang::r-plotthis
    - pwwang::r-scplotter
    - pwwang::r-gglogger

test:
  commands:
    - $R -e "library('biopipen.utils')"

about:
  home: https://github.com/pwwang/biopipen.utils.R
  license: GPL-3
  summary: Common utility R functions for biopipen processes.
  license_family: MIT
  license_file: LICENSE.md
