package:
  name: r-biopipen.utils
  version: 0.3.2

source:
  path: ..

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-bracer
    - r-digest
    - r-doubletfinder
    - r-enrichit
    - r-jsonlite
    - r-logger
    - r-r6
    - r-seurat
    - r-testthat
    - r-tibble
    - r-tidyseurat
    - r-zip
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - pwwang::r-scplotter
    - pwwang::r-seuratdisk
    - r-qs2

  run:
    - r-base
    - r-bracer
    - r-digest
    - r-doubletfinder
    - r-enrichit
    - r-jsonlite
    - r-logger
    - r-r6
    - r-seurat
    - r-testthat
    - r-tibble
    - r-tidyseurat
    - r-zip
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - pwwang::r-scplotter
    - pwwang::r-seuratdisk
    - r-qs2

test:
  commands:
    - $R -e "library('biopipen.utils')"

about:
  home: https://github.com/pwwang/biopipen.utils.R
  license: GPL-3
  summary: Common utility R functions for biopipen processes.
  license_family: MIT
  license_file: LICENSE.md
