package:
  name: r-biopipen.utils
  version: 0.4.5

source:
  path: ..

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-bracer
    - r-digest
    - r-doubletfinder >=2.0.6
    - r-enrichit
    - r-jsonlite
    - r-logger
    - r-r6
    - r-sccdc
    - r-seurat
    - r-testthat
    - r-tibble
    - r-tidyseurat
    - r-zip
    - pwwang::bioconductor-data-packages
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-celda
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - bioconda::bioconductor-destiny
    - bioconda::bioconductor-aucell
    - bioconda::bioconductor-gsva
    - bioconda::bioconductor-gseabase
    - bioconda::bioconductor-genefilter
    - bioconda::bioconductor-ucell
    - bioconda::bioconductor-deseq2
    - bioconda::bioconductor-edger
    - bioconda::bioconductor-complexheatmap
    - bioconda::bioconductor-biobase
    - bioconda::bioconductor-singlecellexperiment
    - bioconda::bioconductor-singler
    - bioconda::bioconductor-summarizedexperiment
    - bioconda::bioconductor-chetah
    - bioconda::bioconductor-scclassify
    - bioconda::bioconductor-scmap
    - bioconda::bioconductor-singscore
    - bioconda::bioconductor-s4vectors
    - r-ggplot2 >4
    - pwwang::r-scplotter
    - pwwang::r-seuratdisk
    - pwwang::r-cellid
    - pwwang::r-hitype
    - pwwang::r-llmcelltype
    - pwwang::r-sccatch
    - pwwang::r-scina
    - pwwang::r-scsorter
    - pwwang::r-seuratwrappers
    - pwwang::r-lict
    - pwwang::r-mllmcelltype
    - r-qs2
    - r-plotly
    - r-htmlwidgets
    - r-glmnet
    - r-hgnchelper
    - r-igraph
    - r-monocle3
    - r-openxlsx
    - r-reshape2
    - r-stringr
    - r-azimuth
    - r-scpred
    - r-withr

  run:
    - r-base
    - r-bracer
    - r-digest
    - r-doubletfinder >=2.0.6
    - r-enrichit
    - r-jsonlite
    - r-logger
    - r-r6
    - r-sccdc
    - r-seurat
    - r-testthat
    - r-tibble
    - r-tidyseurat
    - r-zip
    - pwwang::bioconductor-data-packages
    - bioconda::bioconductor-biocparallel
    - bioconda::bioconductor-celda
    - bioconda::bioconductor-mygene
    - bioconda::bioconductor-scdblfinder
    - bioconda::bioconductor-destiny
    - bioconda::bioconductor-aucell
    - bioconda::bioconductor-gsva
    - bioconda::bioconductor-gseabase
    - bioconda::bioconductor-genefilter
    - bioconda::bioconductor-ucell
    - bioconda::bioconductor-deseq2
    - bioconda::bioconductor-edger
    - bioconda::bioconductor-complexheatmap
    - bioconda::bioconductor-biobase
    - bioconda::bioconductor-singlecellexperiment
    - bioconda::bioconductor-singler
    - bioconda::bioconductor-summarizedexperiment
    - bioconda::bioconductor-chetah
    - bioconda::bioconductor-scclassify
    - bioconda::bioconductor-scmap
    - bioconda::bioconductor-singscore
    - bioconda::bioconductor-s4vectors
    - r-ggplot2 >4
    - pwwang::r-scplotter
    - pwwang::r-seuratdisk
    - pwwang::r-cellid
    - pwwang::r-hitype
    - pwwang::r-llmcelltype
    - pwwang::r-sccatch
    - pwwang::r-scina
    - pwwang::r-scsorter
    - pwwang::r-seuratwrappers
    - pwwang::r-lict
    - pwwang::r-mllmcelltype
    - r-qs2
    - r-plotly
    - r-htmlwidgets
    - r-glmnet
    - r-hgnchelper
    - r-igraph
    - r-monocle3
    - r-openxlsx
    - r-reshape2
    - r-stringr
    - r-azimuth
    - r-scpred
    - r-withr

test:
  commands:
    - $R -e "library('biopipen.utils')"

about:
  home: https://github.com/pwwang/biopipen.utils.R
  license: GPL-3
  summary: Common utility R functions for biopipen processes.
  license_family: MIT
  license_file: LICENSE.md
