#' Run Enrichment Analysis (Over-representation Analysis)
#'
#' Run enrichment analysis on a list of differentially expressed genes (DEGs)
#'
#' @param degs A data frame of DEGs, typically generated by `RunDEAnalysis`
#' @param deg A string specifying the condition for a gene to be considered as differentially expressed
#' @param dbs A string specifying the database to use for enrichment analysis
#' A list of available databases can be found at \url{https://maayanlab.cloud/Enrichr/#libraries}
#' @param cache A string specifying the directory to cache the results
#' Set to `FALSE` to disable caching
#' @param error A boolean specifying whether to throw an error if the enrichment analysis fails
#' @param site A string specifying the Enrichr site to use
#' @param ... Additional arguments to pass to [RunEnrichment]
#' @importFrom utils getFromNamespace
#' @importFrom enrichR setEnrichrSite enrichr
#' @export
#' @examples
#' degs <- suppressWarnings(RunDEAnalysis(SeuratObject::pbmc_small, "groups", "g1", "g2"))
#' RunEnrichment(degs, deg = "abs(avg_log2FC) > 1")
RunEnrichment <- function(
    degs, deg = 'p_val_adj < 0.05', dbs = "KEGG_2021_Human", cache = NULL,
    error = TRUE, site = "Enrichr", ...) {
    if (is.null(cache)) {
        cache <- tempdir()
        # file.remove(cache)
        cache <- dirname(cache)  # a better way to get the tmpdir?
    }

    cached <- get_cached(list(degs, deg, dbs, ...), "biopipen.utils.RunEnrichment", cache)
    if (!is.null(cached$data)) {
        return(cached$data)
    }

    attachEnrichr <- getFromNamespace(".onAttach", "enrichR")
    suppressMessages(attachEnrichr())
    setEnrichrSite(site)

    empty <- data.frame()
    class(empty) <- c("Enrichment", "Enrichr", class(empty))

    sig_degs <- degs %>% filter(!!parse_expr(deg)) %>% pull("gene") %>% unique()
    if (length(sig_degs) == 0) {
        msg <- "[RunEnrichment] No significant DEGs found"
        if (error) {
            stop(msg)
        } else {
            warning(msg)
            return(empty)
        }
    }
    if (length(sig_degs) < 5) {
        msg <- "[RunEnrichment] Too few significant DEGs found"
        if (error) {
            stop(msg)
        } else {
            warning(msg)
            return(empty)
        }
    }

    enriched <- enrichr(sig_degs, dbs)
    out <- do.call(rbind, lapply(names(enriched), function(n) {
        enriched[[n]]$db <- n
        enriched[[n]]
    }))
    class(out) <- c("Enrichment", "Enrichr", class(out))
    out
}


#' Visualize Enrichment
#'
#' Visualize enrichment (over-representation) analysis results
#'
#' @param enrich Enrichment object from RunEnrichment
#' @param outprefix Prefix of the output file
#' @param devpars List of parameters to save the plot
#' @param more_formats Additional formats to save the plot in addition to 'png'
#' @param save_code Whether to save the code to reproduce the plot
#' @param ... Additional arguments to pass to the plot function [scplotter::EnrichmentPlot]
#' @return A ggplot object if 'outprefix' is NULL, otherwise, save the plot to the output directory
#' @export
#' @importFrom plotthis PrepareEnrichrResult
#' @examples
#' \donttest{
#' degs <- suppressWarnings(RunDEAnalysis(SeuratObject::pbmc_small, "groups", "g1", "g2"))
#' enrich <- RunEnrichment(degs, deg = "abs(avg_log2FC) > 1")
#' VizEnrich(enrich)
#' VizEnrich(enrich, plot_type = "dot")
#' VizEnrich(enrich, plot_type = "lollipop")
#' VizEnrich(enrich, plot_type = "network")
#' # VizEnrich(enrich, plot_type = "enrichmap")
#' # VizEnrich(enrich, plot_type = "wordcloud")
#' }
VizEnrich <- function(enrich, outprefix = NULL,
    devpars = list(res = 100), more_formats = c(), save_code = FALSE, ...) {

    stopifnot("[VizEnrich] Can only visualize object from RunEnrichment" = inherits(enrich, "Enrichment"))

    if (save_code) {
        EnrichmentPlot <- gglogger::register(scplotter::EnrichmentPlot, "EnrichmentPlot")
    } else {
        EnrichmentPlot <- scplotter::EnrichmentPlot
    }

    if (inherits(enrich, "Enrichr")) {
        enrich <- PrepareEnrichrResult(enrich)
    }

    p <- EnrichmentPlot(enrich, split_by = "db", ...)

    if (!is.null(outprefix)) {
        formats <- unique(c("png", more_formats))
        save_plot(p, outprefix, formats = formats, devpars = devpars)
        if (save_code) {
            args <- list(plot = p,
                setup = c("library(rlang)", "library(dplyr)", "library(gglogger)", "library(scplotter)", "load('data.RData')"),
                prefix = outprefix)
            args <- c(args, setdiff(ls(), c("p", "args", "formats", "devpars", "more_formats", "save_code", "outprefix")))
            do.call(save_plotcode, args)
        }
        return(NULL)
    } else {
        return(p)
    }
}
