
#' Save the plot into multiple formats
#'
#' @param plot The plot object
#' @param prefix The prefix of the file
#' The ending `.` is removed from the prefix. So both `/path/to/file` and `/path/to/file.` are valid and will
#' save the files as `/path/to/file.png`, `/path/to/file.pdf` and `/path/to/file.<format>` etc.
#' @param formats The formats to save
#' @param bg The background color
#' @param devpars The device parameters
#' @export
#' @importFrom utils getFromNamespace
#' @import ggplot2
save_plot <- function(plot, prefix, devpars = NULL, bg = "white", formats = c("png", "pdf")) {
    devpars <- devpars %||% list()
    devpars$res <- devpars$res %||% 100
    if (!is.null(attr(plot, "width"))) {
        devpars$width <- devpars$width %||% (attr(plot, "width") * devpars$res)
        devpars$height <- devpars$height %||% (attr(plot, "height") * devpars$res)
    } else {
        devpars$width <- devpars$width %||% 800
        devpars$height <- devpars$height %||% 600
    }

    old_dev <- grDevices::dev.cur()
    prefix <- sub("\\.+$", "", prefix)

    if (utils::compareVersion(as.character(utils::packageVersion("ggplot2")), "4") < 0) {
        plot_dev <- getFromNamespace("plot_dev", "ggplot2")
    } else {
        plot_dev <- getFromNamespace("validate_device", "ggplot2")
    }
    plot_dim <- getFromNamespace("plot_dim", "ggplot2")
    for (fmt in formats) {
        filename = paste0(prefix, ".", fmt)
        dev <- plot_dev(fmt, filename, dpi = devpars$res)
        dim <- plot_dim(c(devpars$width, devpars$height), units = "px", limitsize = FALSE, dpi = devpars$res)
        dev(filename = filename, width = dim[1], height = dim[2], bg = bg)
        print(plot)
        grDevices::dev.off()
    }
    on.exit(utils::capture.output({
        # restore old device unless null device
        if (old_dev > 1) grDevices::dev.set(old_dev)  # nocov
    }))
}


#' Save the plot code and data to reproduce the plot
#'
#' The plot should be generated by functions that registered by [gglogger::register]
#'
#' @param plot The plot object
#' @param prefix The prefix of the file
#' The ending `.` is removed from the prefix. So both `/path/to/file` and `/path/to/file.` are valid and will
#' save the files as `/path/to/file.code.zip`.
#' @param setup The code to setup the environment for the plot generation
#' @param ... The names of the variables to save from the environment
#' @param auto_data_setup Whether to automatically save the variables from the environment
#' @param envir The environment to save the variables from
#' @export
#' @importFrom rlang dots_n
save_plotcode <- function(plot, prefix, setup = NULL, ..., auto_data_setup = TRUE, envir = parent.frame()) {
    if (is.null(plot$logs)) {
        stop("The plot object does not have logs, did you use gglogger?")
    }
    dn <- dots_n(...)
    if (dn > 0 && auto_data_setup) {
        setup <- c(setup, 'load("data.RData")')
    }
    code <- plot$logs$gen_code(setup = setup)
    prefix <- sub("\\.+$", "", prefix)

    codedir <- paste0(prefix, ".code")
    dir.create(codedir, showWarnings = FALSE)
    codefile <- file.path(codedir, "plot.R")
    writeLines(code, codefile)
    if (dn > 0) {
        save(..., file = file.path(codedir, "data.RData"), envir = envir)
    }

    zip_file <- paste0(prefix, ".code.zip")
    zip::zip(
        zip_file,
        if (dn > 0) c("plot.R", "data.RData") else "plot.R",
        root = codedir
    )
    unlink(codedir, recursive = TRUE)
}
